version: 0.0
os: linux
files:
 - source: '/'
   destination: /var/app/current

permissions:
  - object: /var/app/current/manage.py
    owner: ec2-user
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
    - location: appspec/set_up_venv.sh
      runas: ec2-user
    - location: appspec/load_code_and_files.sh
      runas: ec2-user
    - location: appspec/db_data_reload.sh
      runas: ec2-user
    - location: appspec/gunicorn.sh
      runas: ec2-user
    - location: appspec/apache.sh
      runas: root
