version: 0.0
os: linux
files:
 - source: '/'
   destination: /var/app/current

permissions:
  - object: /var/app/current/manage.py
    owner: ec2-user
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
    - location: appspec/after_install.sh
      runas: ec2-user
    - location: appspec/after_install_super.sh
      runas: root
