version: 0.0
os: linux
files:
 - source: '*'
   destination: /var/app/current

permissions:
  - object: /var/app/current/manage.py
    owner: ec2-user
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
    - location: .platform/hooks/prebuild/install_dependencies
      timeout: 300
      runas: root
    - location: .platform/hooks/predeploy/start_server
      timeout: 300
      runas: root
