version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - pip install -r requirements.txt
      - cd partisan/
      - npm install gulp -g
      - npm i
      - echo "Install phase complete."
  pre_build:
    commands:
      # Discover and run unit tests. For more information, see <https://docs.djangoproject.com/en/2.0/topics/testing/overview/>
      - npm -v
      - gulp -v
      - echo "Prebuild phase complete."
  build:
    commands:
      - gulp build
      - echo "Build phase complete."
  post_build:
    commands:
      - rm -rf node_modules
      - echo "Post-build phase complete."
artifacts:
  files:
    - '*'
    - '**/*'
