# Generated by Django 3.1 on 2020-10-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0004_auto_20201020_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tw_retriever_metadata',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
