# Generated by Django 3.1 on 2020-10-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0006_tweet_google_nlp_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='google_nlp_processed',
            new_name='nlp_processed',
        ),
        migrations.AddField(
            model_name='tweet',
            name='nlp_neutral_sentiment',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
