# Generated by Django 3.1 on 2020-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0008_auto_20201029_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text_hash',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
