# Generated by Django 3.1 on 2020-11-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0009_tweet_text_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_term',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('term', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term'),
        ),
    ]
