# Generated by Django 3.1 on 2020-11-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0011_auto_20201116_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term'),
        ),
    ]
