# Generated by Django 3.1 on 2020-11-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0012_auto_20201116_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='pie_stat_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='pie_chart_sentiment_stat',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('neutral_sentiment_aggregate', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('mixed_sentiment_aggregate', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('positive_sentiment_aggregate', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('negative_sentiment_aggregate', models.DecimalField(decimal_places=5, max_digits=6, null=True)),
                ('processed_records_count', models.BigIntegerField(null=True)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='statistic_of', to='partisan.search_term')),
            ],
        ),
    ]
