# Generated by Django 3.1 on 2020-12-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0013_auto_20201117_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='reddit_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('text', models.CharField(max_length=10000, null=True)),
                ('nlp_processed', models.BooleanField(default=False)),
                ('nlp_neutral_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_positive_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_negative_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_mixed_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('pie_stat_processed', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term')),
            ],
        ),
        migrations.CreateModel(
            name='reddit_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(editable=False, max_length=32)),
                ('text', models.CharField(max_length=10000)),
                ('text_hash', models.CharField(max_length=128, null=True, unique=True)),
                ('nlp_processed', models.BooleanField(default=False)),
                ('nlp_neutral_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_positive_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_negative_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_mixed_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('pie_stat_processed', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term')),
            ],
        ),
    ]
