# Generated by Django 3.1 on 2020-12-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0014_reddit_comment_reddit_submission_subreddit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddit_submission',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term'),
        ),
        migrations.DeleteModel(
            name='subreddit',
        ),
    ]
