# Generated by Django 3.1 on 2020-12-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0015_auto_20201215_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddit_comment',
            name='text',
            field=models.CharField(max_length=4750),
        ),
        migrations.AlterField(
            model_name='reddit_submission',
            name='text',
            field=models.CharField(max_length=4750, null=True),
        ),
    ]
