# Generated by Django 3.1 on 2020-12-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0017_pull_configuration_sentiment_process_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pie_chart_sentiment_stat',
            name='data_source',
            field=models.CharField(choices=[('re', 'Reddit'), ('tw', 'Twitter')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pull_configuration',
            name='term_name',
            field=models.CharField(help_text='If searching a subreddit, DO NOT prefix with "r/".', max_length=255, unique=True),
        ),
    ]
