# Generated by Django 3.1 on 2021-01-19 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0019_auto_20201222_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=256, null=True, unique=True)),
                ('outlet', models.CharField(max_length=256, null=True, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default='1970-01-01 00:00:00+00:00')),
                ('pie_stat_processed', models.BooleanField(default=False)),
                ('nlp_processed', models.BooleanField(default=False)),
                ('nlp_neutral_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_positive_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_negative_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_mixed_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term')),
            ],
        ),
    ]
