# Generated by Django 3.1 on 2021-01-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0019_auto_20201222_0812'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE UNIQUE INDEX term_source ON partisan_pull_configuration (term_name, data_source)',
            'DROP INDEX term_source ON partisan_pull_configuration'
        )
    ]
