# Generated by Django 3.1 on 2021-01-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0020_add_source_term_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_outlet',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('outlet_name', models.CharField(max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='nyt_retriever_metadata',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('val', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pie_chart_sentiment_stat',
            name='data_source',
            field=models.CharField(choices=[('re', 'Reddit'), ('tw', 'Twitter'), ('nt', 'New York Times')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pull_configuration',
            name='data_source',
            field=models.CharField(choices=[('re', 'Reddit'), ('tw', 'Twitter'), ('nt', 'New York Times')], default='re', max_length=2),
        ),
        migrations.AlterField(
            model_name='pull_configuration',
            name='term_name',
            field=models.CharField(help_text='If searching a subreddit, DO NOT prefix with "r/".', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentiment_process_configuration',
            name='data_source',
            field=models.CharField(choices=[('re', 'Reddit'), ('tw', 'Twitter'), ('nt', 'New York Times')], default='re', max_length=2),
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default='1970-01-01 00:00:00+00:00')),
                ('pie_stat_processed', models.BooleanField(default=False)),
                ('nlp_processed', models.BooleanField(default=False)),
                ('nlp_neutral_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_positive_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_negative_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('nlp_mixed_sentiment', models.DecimalField(decimal_places=20, max_digits=30, null=True)),
                ('news_outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='partisan.news_outlet')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='partisan.search_term')),
            ],
        ),
    ]
