# Generated by Django 3.1 on 2021-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0021_auto_20210121_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
