# Generated by Django 3.1 on 2021-01-22 00:41

from django.db import migrations
from django.db.migrations import migration


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0024_auto_20210121_1639'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE partisan_pie_chart_sentiment_stat ADD UNIQUE INDEX term_source(term_id, data_source);',
            'DROP INDEX term_source ON partisan_pie_chart_sentiment_stat'
        )
    ]
