# Generated by Django 3.1 on 2021-01-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0025_add_sentiment_stat_composite_index'),
        ('partisan', '0021_reddit_data_created_date_population'),
    ]

    operations = [
    ]
