# Generated by Django 3.1 on 2021-01-22 00:41

from django.db import migrations
from django.db.migrations import migration


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0027_historical_sentiment_stat'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE partisan_historical_sentiment_stat ADD UNIQUE INDEX monthly_stat(term_id, data_source, month_dt);',
            'DROP INDEX monthly_stat ON partisan_historical_sentiment_stat'
        )
    ]
