# Generated by Django 3.1 on 2021-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partisan', '0028_add_over_time_stat_composite_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='historical_stat_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reddit_comment',
            name='historical_stat_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reddit_submission',
            name='historical_stat_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='historical_stat_processed',
            field=models.BooleanField(default=False),
        ),
    ]
